# Generated by Django 4.2.2 on 2023-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0003_alter_objections_textobjections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objections',
            options={'verbose_name': 'Возражение', 'verbose_name_plural': 'Возражения'},
        ),
    ]
