# Generated by Django 4.2.2 on 2023-06-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0004_alter_objections_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objections',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
